# netlify.toml

[build]
  command = "npm install; npm run build"
  publish = "dist"  # ou o diretório onde os arquivos de construção estão localizados

[[redirects]]
  from = "/api/*"
  to = "https://mega-back-aaia.onrender.com/api/:splat"
  status = 200
  force = true
